########################################################
# creates postgres sql database image and pgadmin4 image
# login db: postgres:postgres hostname: postgres
# login pgadmin: admin@developer-blog.net:admin port 5555
########################################################
version: '3'
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
